# Exported from Render on 2024-05-08T17:34:59Z
services:
- type: web
  name: santander-dev-week-2024
  runtime: node
  repo: https://github.com/vladmirprates/santander-dev-week-2024
  plan: free
  envVars:
  - key: OPEN_API_KEY
    sync: false
  - key: SERVER_PORT
    sync: false
  - key: M2_HOME
    sync: false
  - key: M2
    sync: false
  - key: GRADLE_HOME
    sync: false
  region: oregon
  buildCommand: yarn
  startCommand: yanr start
version: "1"
